### ISSUE TITLE
'Scene' object has no attribute 'update'

### ISSUE THREAD

**Issue by thedaemon** [xbodya13/free_ik_doc#1]
Not sure what this is, using daily 2.8 build from today. Let me know if you need more details. This happens pretty much when doing anything. Cheers.

Traceback (most recent call last):
  File "/home/thedaemon/.config/blender/2.80/scripts/addons/free_ik.py", line 5019, in execute
    context.scene.update()
**AttributeError: 'Scene' object has no attribute 'update'**

location: <unknown location>:-1

**Comment by xbodya13** [comment]
Hi.
I just updated the script,does it work now?

**Comment by thedaemon** [comment]
Yes sorry that I haven't replied sooner. Thank you for the speedy fix.
